/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#590028",
        "on-secondary-fixed": "#2e1221",
        "on-primary-fixed-variant": "#8f0044",
        error: "#ffb4ab",
        "primary-fixed-dim": "#ffb1c4",
        "tertiary-container": "#a178ff",
        "on-tertiary-container": "#34007f",
        "on-secondary-container": "#d6a9bc",
        "inverse-primary": "#ba005b",
        "on-primary": "#65002e",
        "on-primary-fixed": "#3f001a",
        "on-tertiary-fixed-variant": "#5700c9",
        "tertiary-fixed-dim": "#d1bcff",
        "on-surface-variant": "#e5bcc5",
        background: "#131313",
        "on-surface": "#e5e2e1",
        "surface-tint": "#ffb1c4",
        primary: "#ffb1c4",
        "surface-dim": "#131313",
        "on-tertiary-fixed": "#23005b",
        "surface-bright": "#3a3939",
        "outline-variant": "#5c3f46",
        "surface-container-highest": "#353534",
        "secondary-fixed-dim": "#e9bacd",
        "secondary-container": "#5f3c4d",
        "on-error-container": "#ffdad6",
        "surface-container": "#201f1f",
        "inverse-surface": "#e5e2e1",
        "primary-container": "#ff4a8d",
        "error-container": "#93000a",
        "surface-container-low": "#1c1b1b",
        "surface-container-lowest": "#0e0e0e",
        outline: "#ac878f",
        secondary: "#e9bacd",
        "secondary-fixed": "#ffd8e7",
        surface: "#131313",
        "on-tertiary": "#3c0090",
        "tertiary-fixed": "#e9ddff",
        "on-error": "#690005",
        "primary-fixed": "#ffd9e1",
        "on-secondary-fixed-variant": "#5f3c4d",
        "on-secondary": "#462736",
        "inverse-on-surface": "#313030",
        tertiary: "#d1bcff",
        "surface-container-high": "#2a2a2a",
        "on-background": "#e5e2e1",
        "surface-variant": "#353534",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        xs: "4px",
        xl: "80px",
        base: "8px",
        "margin-desktop": "64px",
        gutter: "24px",
        md: "24px",
        sm: "12px",
        "margin-mobile": "16px",
        lg: "48px",
      },
      fontFamily: {
        "headline-md": ["Playfair Display"],
        "label-md": ["Geist"],
        "headline-lg-mobile": ["Playfair Display"],
        "body-md": ["Geist"],
        "headline-lg": ["Playfair Display"],
        "code-sm": ["Geist"],
        "headline-xl": ["Playfair Display"],
        "body-lg": ["Geist"],
      },
      fontSize: {
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-md": [
          "14px",
          { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "1.2", fontWeight: "700" },
        ],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "700" }],
        "code-sm": ["12px", { lineHeight: "1.4", fontWeight: "400" }],
        "headline-xl": [
          "64px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "900" },
        ],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
